version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    working_dir: /usr/src
    volumes:
      - .:/usr/src
    depends_on:
      - db
    environment:
      - SQL_HOST=db
